<a href="https://colab.research.google.com/github/ManoloVM21/MachineLearningTeam4/blob/main/Module%2003%20-%20XGBoost/Manolo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install lets-plot
from lets_plot import *
import pandas as pd
housing = pd.read_csv(
    "https://raw.githubusercontent.com/byui-cse/cse450-course/master/data/housing.csv"
)

Collecting lets-plot
  Downloading lets_plot-4.8.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (12 kB)
Collecting pypng (from lets-plot)
  Downloading pypng-0.20220715.0-py3-none-any.whl.metadata (13 kB)
Collecting palettable (from lets-plot)
  Downloading palettable-3.3.3-py2.py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from lets-plot) (11.3.0)
Downloading lets_plot-4.8.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (6.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.8/6.8 MB 26.7 MB/s eta 0:00:00
Downloading palettable-3.3.3-py2.py3-none-any.whl (332 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 332.3/332.3 kB 25.8 MB/s eta 0:00:00
Downloading pypng-0.20220715.0-py3-none-any.whl (58 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.1/58.1 kB 4.6 MB/s eta 0:00:00
Installing collected packages: pypng, palettable, lets-plot
Successfully installed lets-plot-4.8.2 palettable-3.3.3 pypng-0.20220715.0

In [ ]:
housing.columns

Index(['id', 'date', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot',
       'floors', 'waterfront', 'view', 'condition', 'grade', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode', 'lat', 'long',
       'sqft_living15', 'sqft_lot15', 'price'],
      dtype='object')

In [ ]:
housing.describe()

,id,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,price
count,2.000000e+04,20000.000000,20000.000000,20000.000000,2.000000e+04,20000.00000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.00000,2.000000e+04
mean,4.580297e+09,3.370200,2.115750,2079.883100,1.501533e+04,1.49645,0.007550,0.234900,3.409700,7.657700,1790.232900,289.650200,1971.100150,82.732150,98077.876850,47.559970,-122.213897,1986.387500,12748.96040,5.394367e+05
std,2.875295e+09,0.931931,0.770134,919.433672,3.970135e+04,0.54095,0.086564,0.767692,0.651895,1.175287,829.587101,441.537072,29.374008,397.872344,53.438026,0.138517,0.140649,685.211515,27076.48904,3.664334e+05
min,1.000102e+06,0.000000,0.000000,290.000000,5.200000e+02,1.00000,0.000000,0.000000,1.000000,1.000000,290.000000,0.000000,1900.000000,0.000000,98001.000000,47.155900,-122.519000,399.000000,651.00000,7.500000e+04
25%,2.123049e+09,3.000000,1.750000,1430.000000,5.040000e+03,1.00000,0.000000,0.000000,3.000000,7.000000,1200.000000,0.000000,1951.750000,0.000000,98033.000000,47.470675,-122.328000,1490.000000,5100.00000,3.220000e+05
50%,3.904955e+09,3.000000,2.250000,1910.000000,7.620000e+03,1.50000,0.000000,0.000000,3.000000,7.000000,1560.000000,0.000000,1975.000000,0.000000,98065.000000,47.571450,-122.230000,1840.000000,7622.00000,4.500000e+05
75%,7.309825e+09,4.000000,2.500000,2550.000000,1.071000e+04,2.00000,0.000000,0.000000,4.000000,8.000000,2210.000000,560.000000,1997.000000,0.000000,98117.000000,47.678000,-122.124000,2360.000000,10088.25000,6.416250e+05
max,9.900000e+09,33.000000,8.000000,13540.000000,1.164794e+06,3.50000,1.000000,4.000000,5.000000,13.000000,9410.000000,4820.000000,2015.000000,2015.000000,98199.000000,47.777600,-121.315000,6210.000000,871200.00000,7.700000e+06

# Base Model

RMSE: 128447.44477482521
R2: 0.8832500720937965

Feature Importance

          feature  importance
    5      waterfront    0.433137
    8           grade    0.364288
    6            view    0.047243
    2     sqft_living    0.045541
    14            lat    0.034736
    15           long    0.017579
    12   yr_renovated    0.009094
    11       yr_built    0.008197
    1       bathrooms    0.007895
    16  sqft_living15    0.007196
    13        zipcode    0.006838
    7       condition    0.004216
    9      sqft_above    0.003846
    4          floors    0.002482
    3        sqft_lot    0.002428
    10  sqft_basement    0.002180
    17     sqft_lot15    0.001951
    0        bedrooms    0.001153

In [ ]:
from sklearn.model_selection import train_test_split
x = housing.drop(columns=['price','id','date'])
y = housing['price']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=67)

In [ ]:
from xgboost import XGBRegressor
model = XGBRegressor(
    n_estimators=5000,
    learning_rate=0.05,
    n_jobs=4
)
model.fit(x_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=5000,
             n_jobs=4, num_parallel_tree=None, ...)

In [ ]:
from sklearn.metrics import root_mean_squared_error, r2_score
from lets_plot import *
y_preds = model.predict(x_test)

print(f"RMSE: {root_mean_squared_error(y_test, y_preds)}")
print(f'R2: {r2_score(y_test, y_preds)}')

# Get feature importances
feature_importances = model.feature_importances_
feature_names = x_train.columns

# Create a DataFrame for better visualization
importance_df = pd.DataFrame({
    'feature': feature_names,
    'importance': feature_importances
}).sort_values(by='importance', ascending=False)

# Print feature importances
print(f'Feature Importance')
print(importance_df)

# Plot feature importances
p = ggplot(importance_df, aes(x='reorder(feature, importance)', y='importance')) + \
    geom_bar(stat='identity', fill='steelblue') + \
    coord_flip() + \
    labs(x='Feature', y='Importance', title='Feature Importances from XGBoost Model')
p.show()

RMSE: 128447.44477482521
R2: 0.8832500720937965
Feature Importance
          feature  importance
5      waterfront    0.433137
8           grade    0.364288
6            view    0.047243
2     sqft_living    0.045541
14            lat    0.034736
15           long    0.017579
12   yr_renovated    0.009094
11       yr_built    0.008197
1       bathrooms    0.007895
16  sqft_living15    0.007196
13        zipcode    0.006838
7       condition    0.004216
9      sqft_above    0.003846
4          floors    0.002482
3        sqft_lot    0.002428
10  sqft_basement    0.002180
17     sqft_lot15    0.001951
0        bedrooms    0.001153

# +3 Features

RMSE: 83657.95355616572
R2: 0.8855265175555234

Feature Importance

          feature  importance
    5      waterfront    0.421677
    18  luxury_metric    0.258821
    8           grade    0.122379
    14            lat    0.058327
    2     sqft_living    0.023920
    21      house_age    0.020731
    12   yr_renovated    0.014492
    15           long    0.011464
    16  sqft_living15    0.010669
    13        zipcode    0.010026
    6            view    0.008923
    9      sqft_above    0.007889
    19           year    0.006682
    11       yr_built    0.003875
    3        sqft_lot    0.003368
    4          floors    0.003257
    17     sqft_lot15    0.003162
    10  sqft_basement    0.002808
    7       condition    0.002623
    1       bathrooms    0.002118
    20     sale_month    0.001495
    0        bedrooms    0.001295

In [ ]:
housing['luxury_metric']  = housing['view']+housing['grade']+housing['condition']

In [ ]:
housing = housing[housing['bedrooms'] <30]

In [ ]:
housing['date'] = pd.to_datetime(housing['date'], format='%Y%m%dT%H%M%S')
housing['year'] = housing['date'].dt.year
housing['sale_month'] = housing['date'].dt.month

/tmp/ipython-input-1484051562.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  housing['date'] = pd.to_datetime(housing['date'], format='%Y%m%dT%H%M%S')
/tmp/ipython-input-1484051562.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  housing['year'] = housing['date'].dt.year
/tmp/ipython-input-1484051562.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  housing['sale_month'] = housing['date'].dt.month

In [ ]:
housing['house_age'] = housing['year'] - housing['yr_built']

/tmp/ipython-input-3794025432.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  housing['house_age'] = housing['year'] - housing['yr_built']

In [ ]:
housing = housing[housing['bathrooms']<3]

In [ ]:
from sklearn.model_selection import train_test_split
x = housing.drop(columns=['price','id','date'])
y = housing['price']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=67)

In [ ]:
from xgboost import XGBRegressor
model = XGBRegressor(
    n_estimators=5000,
    learning_rate=0.05,
    n_jobs=4
)
model.fit(x_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=5000,
             n_jobs=4, num_parallel_tree=None, ...)

In [ ]:
from sklearn.metrics import root_mean_squared_error, r2_score
from lets_plot import *
y_preds = model.predict(x_test)

print(f"RMSE: {root_mean_squared_error(y_test, y_preds)}")
print(f'R2: {r2_score(y_test, y_preds)}')

# Get feature importances
feature_importances = model.feature_importances_
feature_names = x_train.columns

# Create a DataFrame for better visualization
importance_df = pd.DataFrame({
    'feature': feature_names,
    'importance': feature_importances
}).sort_values(by='importance', ascending=False)

# Print feature importances
print(f'Feature Importance')
print(importance_df)

# Plot feature importances
p = ggplot(importance_df, aes(x='reorder(feature, importance)', y='importance')) + \
    geom_bar(stat='identity', fill='steelblue') + \
    coord_flip() + \
    labs(x='Feature', y='Importance', title='Feature Importances from XGBoost Model')
p.show()

RMSE: 83657.95355616572
R2: 0.8855265175555234
Feature Importance
          feature  importance
5      waterfront    0.421677
18  luxury_metric    0.258821
8           grade    0.122379
14            lat    0.058327
2     sqft_living    0.023920
21      house_age    0.020731
12   yr_renovated    0.014492
15           long    0.011464
16  sqft_living15    0.010669
13        zipcode    0.010026
6            view    0.008923
9      sqft_above    0.007889
19           year    0.006682
11       yr_built    0.003875
3        sqft_lot    0.003368
4          floors    0.003257
17     sqft_lot15    0.003162
10  sqft_basement    0.002808
7       condition    0.002623
1       bathrooms    0.002118
20     sale_month    0.001495
0        bedrooms    0.001295

In [ ]:
results_df = pd.DataFrame({
    'Actual Price': y_test,
    'Predicted Price': y_preds
})

# Create a scatter plot of Actual vs. Predicted Prices
p = ggplot(results_df, aes(x='Actual Price', y='Predicted Price')) + \
    geom_point(alpha=0.5) + \
    geom_abline(intercept=0, slope=1, color='red', linetype='dashed') + \
    labs(title='Actual vs. Predicted Housing Prices') + \
    xlab('Actual Price') + \
    ylab('Predicted Price')

p.show()

# 2nd Model

RMSE: 89954.25897010307
R2: 0.8660517742637902

Feature Importance

          feature  importance
    5      waterfront    0.257369
    18  luxury_metric    0.227171
    14            lat    0.160465
    8           grade    0.091103
    2     sqft_living    0.085179
    6            view    0.021670
    12   yr_renovated    0.020529
    15           long    0.019093
    16  sqft_living15    0.018304
    19           year    0.013424
    13        zipcode    0.011578
    21      house_age    0.011115
    9      sqft_above    0.009123
    3        sqft_lot    0.006812
    17     sqft_lot15    0.006354
    11       yr_built    0.006016
    7       condition    0.005870
    24       bath_bed    0.004873
    1       bathrooms    0.004247
    4          floors    0.003851
    23       lot_diff    0.003810
    22      sqft_diff    0.003627
    10  sqft_basement    0.003472
    20     sale_month    0.003088
    0        bedrooms    0.001854

In [ ]:
housing['sqft_diff'] = housing['sqft_living'] - housing['sqft_living15']
housing['lot_diff'] = housing['sqft_lot'] - housing['sqft_lot15']

In [ ]:
import numpy as np
housing['log_price'] = np.log1p(housing['price'])
housing.drop(columns=['price'], inplace=True)

In [ ]:
housing = housing[(housing['bedrooms'] >0)&(housing['bathrooms']>0)]
housing['bath_bed'] = housing['bathrooms']/housing['bedrooms']

/tmp/ipython-input-916637355.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  housing['bath_bed'] = housing['bathrooms']/housing['bedrooms']

In [ ]:
from sklearn.model_selection import train_test_split
x = housing.drop(columns=['log_price','id','date','sqft_living','sqft_living15','sqft_lot','sqft_lot15','bathrooms','bedrooms'])
y = housing['log_price']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=67)

In [ ]:
housing.describe()

,id,date,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,...,sqft_living15,sqft_lot15,luxury_metric,year,sale_month,house_age,sqft_diff,lot_diff,log_price,bath_bed
count,1.755600e+04,17556,17556.00000,17556.000000,17556.000000,1.755600e+04,17556.000000,17556.000000,17556.000000,17556.000000,...,17556.000000,17556.000000,17556.000000,17556.000000,17556.000000,17556.00000,17556.000000,1.755600e+04,17556.000000,17556.000000
mean,4.599420e+09,2014-10-29 08:10:05.331510528,3.25655,1.929896,1898.807416,1.375601e+04,1.442384,0.005639,0.182217,3.428514,...,1897.076099,12068.085441,11.080087,2014.322226,6.588403,45.31727,1.731317,1.687924e+03,12.966239,0.611000
min,1.200019e+06,2014-05-02 00:00:00,1.00000,0.500000,370.000000,5.200000e+02,1.000000,0.000000,0.000000,1.000000,...,399.000000,651.000000,5.000000,2014.000000,1.000000,-1.00000,-2310.000000,-3.268790e+05,11.264477,0.125000
25%,2.129700e+09,2014-07-22 00:00:00,3.00000,1.500000,1370.000000,5.040000e+03,1.000000,0.000000,0.000000,3.000000,...,1460.000000,5100.000000,10.000000,2014.000000,4.000000,22.00000,-260.000000,-4.110000e+02,12.639825,0.500000
50%,3.905100e+09,2014-10-16 00:00:00,3.00000,2.000000,1810.000000,7.560000e+03,1.000000,0.000000,0.000000,3.000000,...,1780.000000,7600.000000,11.000000,2014.000000,6.000000,44.00000,0.000000,0.000000e+00,12.962197,0.583333
75%,7.338000e+09,2015-02-17 00:00:00,4.00000,2.500000,2340.000000,1.032000e+04,2.000000,0.000000,0.000000,4.000000,...,2250.000000,9884.500000,12.000000,2015.000000,9.000000,64.00000,220.000000,6.080000e+02,13.279369,0.750000
max,9.900000e+09,2015-05-27 00:00:00,10.00000,2.750000,6840.000000,1.164794e+06,3.500000,1.000000,4.000000,5.000000,...,5790.000000,438213.000000,21.000000,2015.000000,12.000000,115.00000,3720.000000,1.148064e+06,15.002744,2.500000
std,2.874042e+09,NaN,0.83277,0.588200,705.060535,3.384174e+04,0.527915,0.074884,0.673969,0.657680,...,593.549853,24230.636979,1.412186,0.467342,3.117063,28.86348,476.457396,2.224031e+04,0.465119,0.194711

In [ ]:
from xgboost import XGBRegressor
model = XGBRegressor(
    n_estimators=5000,
    learning_rate=0.05,
    n_jobs=4
)
model.fit(x_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=5000,
             n_jobs=4, num_parallel_tree=None, ...)

In [ ]:
from sklearn.metrics import root_mean_squared_error, r2_score
from lets_plot import *
y_preds = model.predict(x_test)

print(f"RMSE: {root_mean_squared_error(np.expm1(y_test), np.expm1(y_preds))}")
print(f'R2: {r2_score(y_test, y_preds)}')

# Get feature importances
feature_importances = model.feature_importances_
feature_names = x_train.columns

# Create a DataFrame for better visualization
importance_df = pd.DataFrame({
    'feature': feature_names,
    'importance': feature_importances
}).sort_values(by='importance', ascending=False)

# Print feature importances
print(f'Feature Importance')
print(importance_df)

# Plot feature importances
p = ggplot(importance_df, aes(x='reorder(feature, importance)', y='importance')) + \
    geom_bar(stat='identity', fill='steelblue') + \
    coord_flip() + \
    labs(x='Feature', y='Importance', title='Feature Importances from XGBoost Model')
p.show()

RMSE: 90441.81738288813
R2: 0.862140108583844
Feature Importance
          feature  importance
12  luxury_metric    0.357695
10            lat    0.174740
4           grade    0.155100
1      waterfront    0.073986
5      sqft_above    0.043665
6   sqft_basement    0.036458
2            view    0.021778
11           long    0.021656
8    yr_renovated    0.019174
13           year    0.018393
9         zipcode    0.016713
15      house_age    0.012345
7        yr_built    0.009045
18       bath_bed    0.008744
17       lot_diff    0.008551
16      sqft_diff    0.006466
3       condition    0.005477
0          floors    0.005024
14     sale_month    0.004991

In [ ]:
results_df = pd.DataFrame({
    'Actual Price': np.expm1(y_test),
    'Predicted Price': np.expm1(y_preds)
})

# Create a scatter plot of Actual vs. Predicted Prices
p = ggplot(results_df, aes(x='Actual Price', y='Predicted Price')) + \
    geom_point(alpha=0.5) + \
    geom_abline(intercept=0, slope=1, color='red', linetype='dashed') + \
    labs(title='Actual vs. Predicted Housing Prices') + \
    xlab('Actual Price') + \
    ylab('Predicted Price')

p.show()

#3rd Model

In [ ]:
mean_prices_by_zip = housing.groupby('zipcode')['log_price'].mean().rename('mean_price_zip')
housing = housing.merge(mean_prices_by_zip, on='zipcode', how='left')

In [ ]:
housing.drop(columns=['mean_price_zip_x'], inplace=True)

In [ ]:
from sklearn.cluster import KMeans
housing['geocluster'] = KMeans(n_clusters=10, random_state=0, n_init='auto').fit_predict(housing[['lat']].div(housing['long'], axis=0))

In [ ]:
housing

,id,date,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,...,luxury_metric,year,sale_month,house_age,sqft_diff,lot_diff,log_price,bath_bed,mean_price_zip_y,geocluster
0,3279000420,2015-01-15,3,1.75,1460,7800,1.0,0,0,2,...,9,2015,1,36,150,-65,12.358798,0.583333,12.488886,5
1,194000575,2014-10-14,4,1.00,1340,5800,1.5,0,2,3,...,12,2014,10,100,-560,0,13.028055,0.250000,13.225639,4
2,2115510160,2014-12-08,3,1.75,1440,8050,1.0,0,0,3,...,11,2014,12,29,-350,562,12.464394,0.583333,12.488886,5
3,7522500005,2014-08-15,2,1.50,1780,4750,1.0,0,0,4,...,11,2014,8,67,90,-1212,13.226725,0.750000,13.190419,3
4,3787000140,2014-09-01,3,2.25,1780,9969,1.0,0,0,3,...,11,2014,9,29,-170,1995,13.017005,0.750000,13.018289,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17551,5272200045,2014-11-13,3,1.50,1000,6914,1.0,0,0,3,...,10,2014,11,67,0,-33,12.842652,0.500000,12.971715,8
17552,9578500790,2014-11-11,3,2.50,3087,5002,2.0,0,0,3,...,11,2014,11,0,160,-181,12.899097,0.833333,12.488886,5
17553,7202350480,2014-09-30,3,2.50,2120,4780,2.0,0,0,3,...,10,2014,9,10,430,2130,13.262127,0.833333,13.257819,2
17554,1723049033,2014-06-20,1,0.75,380,15000,1.0,0,0,3,...,8,2014,6,51,-790,0,12.409018,0.750000,12.336284,6
17555,6147650280,2015-03-25,4,2.50,3130,5999,2.0,0,0,3,...,10,2015,3,9,110,2,12.660331,0.625000,12.577971,6

In [ ]:
from sklearn.model_selection import train_test_split
x = housing.drop(columns=['log_price','id','date','sqft_living','sqft_living15','sqft_lot','sqft_lot15','bath_bed','view','condition','grade'])
y = housing['log_price']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=67)

In [ ]:
from xgboost import XGBRegressor
model = XGBRegressor(
    n_estimators=5000,
    learning_rate=0.05,
    n_jobs=4
)
model.fit(x_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=5000,
             n_jobs=4, num_parallel_tree=None, ...)

In [ ]:
from sklearn.metrics import root_mean_squared_error, r2_score
from lets_plot import *
y_preds = model.predict(x_test)

print(f"RMSE: {root_mean_squared_error(np.expm1(y_test), np.expm1(y_preds))}")
print(f'R2: {r2_score(y_test, y_preds)}')

# Get feature importances
feature_importances = model.feature_importances_
feature_names = x_train.columns

# Create a DataFrame for better visualization
importance_df = pd.DataFrame({
    'feature': feature_names,
    'importance': feature_importances
}).sort_values(by='importance', ascending=False)

# Print feature importances
print(f'Feature Importance')
print(importance_df)

# Plot feature importances
p = ggplot(importance_df, aes(x='reorder(feature, importance)', y='importance')) + \
    geom_bar(stat='identity', fill='steelblue') + \
    coord_flip() + \
    labs(x='Feature', y='Importance', title='Feature Importances from XGBoost Model')
p.show()

RMSE: 90364.97862764342
R2: 0.8617886223572274
Feature Importance
             feature  importance
17  mean_price_zip_y    0.478400
11     luxury_metric    0.198785
3         waterfront    0.122449
4         sqft_above    0.038244
5      sqft_basement    0.030153
7       yr_renovated    0.022204
9                lat    0.019374
12              year    0.015900
1          bathrooms    0.012319
10              long    0.010709
14         house_age    0.007978
6           yr_built    0.006544
18        geocluster    0.006378
16          lot_diff    0.006368
8            zipcode    0.006201
2             floors    0.005859
15         sqft_diff    0.005055
13        sale_month    0.004039
0           bedrooms    0.003040

In [ ]:
results_df = pd.DataFrame({
    'Actual Price': np.expm1(y_test),
    'Predicted Price': np.expm1(y_preds)
})

# Create a scatter plot of Actual vs. Predicted Prices
p = ggplot(results_df, aes(x='Actual Price', y='Predicted Price')) + \
    geom_point(alpha=0.5) + \
    geom_abline(intercept=0, slope=1, color='red', linetype='dashed') + \
    labs(title='Actual vs. Predicted Housing Prices') + \
    xlab('Actual Price') + \
    ylab('Predicted Price')

p.show()

# Pipeline added

In [ ]:
# Task
import pandas as pd
import numpy as np
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from xgboost import XGBRegressor
from geopy.distance import great_circle
from sklearn.cluster import KMeans
import warnings

# Suppress SettingWithCopyWarning for chained assignments where copies are intentionally made
pd.options.mode.chained_assignment = None

# Define the distance calculation function
def calculate_distance(lat1, lon1, lat2, lon2):
    return great_circle((lat1, lon1), (lat2, lon2)).km

class HousingFeatureEngineer(BaseEstimator, TransformerMixin):
    def __init__(self):
        # Define constants used in feature engineering (like office locations, water bodies, downtowns)
        self.seattle_offices = [
            {"name": "Amazon HQ - Doppler Building", "company": "Amazon", "latitude": 47.615257, "longitude": -122.338356},
            {"name": "Starbucks Headquarters", "company": "Starbucks", "latitude": 47.618064, "longitude": -122.303796},
            {"name": "Microsoft Headquarters", "company": "Microsoft", "latitude": 47.643543, "longitude": -122.130821},
            {"name": "Google Seattle Campus (South Lake Union)", "company": "Google", "latitude": 47.622900, "longitude": -122.336600},
            {"name": "Meta (Facebook) Seattle Office", "company": "Meta", "latitude": 47.623500, "longitude": -122.336500},
            {"name": "Zillow Headquarters", "company": "Zillow", "latitude": 47.620500, "longitude": -122.338000},
            {"name": "Expedia Group Headquarters (Bellevue)", "company": "Expedia", "latitude": 47.610100, "longitude": -122.201500}
        ]

        self.seattle_water_bodies = [
            {"name": "Lake Union", "latitude": 47.6401, "longitude": -122.3366},
            {"name": "Lake Washington", "latitude": 47.6099, "longitude": -122.2155},
            {"name": "Puget Sound", "latitude": 47.6062, "longitude": -122.6035},
            {"name": "Green Lake", "latitude": 47.6749, "longitude": -122.3364},
            {"name": "Mercer Slough", "latitude": 47.5750, "longitude": -122.1950},
            {"name": "Elliott Bay", "latitude": 47.6111, "longitude": -122.3450}
        ]

        self.seattle_downtowns = [
            {"name": "Downtown Core", "latitude": 47.6097, "longitude": -122.3331},
            {"name": "Pioneer Square", "latitude": 47.6022, "longitude": -122.3332},
            {"name": "South Lake Union", "latitude": 47.6222, "longitude": -122.3364}
        ]
        self.mean_prices_by_zip_ = None
        self.kmeans_model_for_geocluster_ = None
        self.overall_mean_log_price_ = None
        self.feature_names_out_ = None # Store output feature names for get_feature_names_out

    def fit(self, X, y=None):
        if y is None:
            raise ValueError("y (original 'price' column) must be provided to the fit method for mean_price_zip calculation.")

        X_copy = X.copy()
        y_copy = y.copy()

        # Log transform y to calculate mean_price_zip
        y_log = np.log1p(y_copy)

        # Calculate mean_price_zip using log_price from training data
        temp_df = X_copy[['zipcode']].copy()
        temp_df['log_price_target'] = y_log
        self.mean_prices_by_zip_ = temp_df.groupby('zipcode')['log_price_target'].mean().rename('mean_price_zip').reset_index()
        self.overall_mean_log_price_ = self.mean_prices_by_zip_['mean_price_zip'].mean()

        # Fit KMeans for geocluster on training data
        self.kmeans_model_for_geocluster_ = KMeans(n_clusters=10, random_state=0, n_init='auto')
        self.kmeans_model_for_geocluster_.fit(X_copy[['lat', 'long']])

        # To get feature_names_out, transform a sample of X and store its columns
        self.feature_names_out_ = self._get_transformed_columns(X_copy).columns.tolist()

        return self

    def _get_transformed_columns(self, X_data):
        # Helper method to apply transformations and get column names
        X_transformed_temp = X_data.copy()

        # --- Add 'selled_again' feature ---
        id_counts = X_transformed_temp['id'].value_counts()
        # --- Add distance-to-office features ---
        for office in self.seattle_offices:
            company_name = office['company']
            office_lat = office['latitude']
            office_long = office['longitude']
            X_transformed_temp[f'distance_to_{company_name}'] = X_transformed_temp.apply(
                lambda row: calculate_distance(row['lat'], row['long'], office_lat, office_long),
                axis=1
            )

        # --- Add distance_to_water (min distance to any water body) ---
        min_distances_to_water = []
        for index, row in X_transformed_temp.iterrows():
            house_lat = row['lat']
            house_long = row['long']
            distances_to_all_water_bodies = []
            for water_body in self.seattle_water_bodies:
                water_lat = water_body['latitude']
                water_long = water_body['longitude']
                distance = calculate_distance(house_lat, house_long, water_lat, water_long)
                distances_to_all_water_bodies.append(distance)
            min_distances_to_water.append(min(distances_to_all_water_bodies))
        X_transformed_temp['distance_to_water'] = min_distances_to_water

        # --- Add min_distance_to_downtown ---
        min_distances_to_downtown = []
        for index, row in X_transformed_temp.iterrows():
            house_lat = row['lat']
            house_long = row['long']
            distances_to_all_downtowns = []
            for downtown_location in self.seattle_downtowns:
                downtown_lat = downtown_location['latitude']
                downtown_long = downtown_location['longitude']
                distance = calculate_distance(house_lat, house_long, downtown_lat, downtown_long)
                distances_to_all_downtowns.append(distance)
            min_distances_to_downtown.append(min(distances_to_all_downtowns))
        X_transformed_temp['min_distance_to_downtown'] = min_distances_to_downtown

        # --- Add 'luxury_metric' feature ---
        X_transformed_temp['luxury_metric'] = X_transformed_temp['view'] + X_transformed_temp['grade'] + X_transformed_temp['condition']

        # --- Date-based features ('year', 'sale_month', 'house_age_at_sale') ---
        if 'date' in X_transformed_temp.columns:
            if not pd.api.types.is_datetime64_any_dtype(X_transformed_temp['date']):
                X_transformed_temp['date'] = pd.to_datetime(X_transformed_temp['date'], format='%Y%m%dT%H%M%S')
            X_transformed_temp['sale_year'] = X_transformed_temp['date'].dt.year
            X_transformed_temp['sale_month'] = X_transformed_temp['date'].dt.month
            X_transformed_temp['house_age_at_sale'] = X_transformed_temp['sale_year'] - X_transformed_temp['yr_built']
        else:
            X_transformed_temp['sale_year'] = 0
            X_transformed_temp['sale_month'] = 0
            X_transformed_temp['house_age_at_sale'] = 0

        # --- Add 'sqft_diff' and 'lot_diff' ---
        X_transformed_temp['sqft_diff'] = X_transformed_temp['sqft_living'] - X_transformed_temp['sqft_living15']
        X_transformed_temp['lot_diff'] = X_transformed_temp['sqft_lot'] - X_transformed_temp['sqft_lot15']

        # --- Add 'bath_bed' ---
        X_transformed_temp['bath_bed'] = X_transformed_temp['bathrooms'] / X_transformed_temp['bedrooms'].replace(0, np.nan)
        X_transformed_temp['bath_bed'].fillna(0, inplace=True)

        # --- Add 'mean_price_zip' ---
        if self.mean_prices_by_zip_ is not None:
            X_transformed_temp = X_transformed_temp.merge(self.mean_prices_by_zip_, on='zipcode', how='left')
            X_transformed_temp['mean_price_zip'].fillna(self.overall_mean_log_price_, inplace=True)

        # --- Add 'geocluster' ---
        if self.kmeans_model_for_geocluster_ is not None and 'lat' in X_transformed_temp.columns and 'long' in X_transformed_temp.columns:
            X_transformed_temp['geocluster'] = self.kmeans_model_for_geocluster_.predict(X_transformed_temp[['lat', 'long']])

        # Define columns to drop after feature engineering
        columns_to_drop = [
            "id", "date", # Identifiers, original date
            "view", "condition", "grade",# now part of 'luxury_metric'
            'bath_bed',
            "yr_built", "yr_renovated", # Replaced by house_age_at_sale or less important
            "sale_year", # Derived from 'date', potentially redundant with 'house_age_at_sale'
        ]

        X_transformed_temp = X_transformed_temp.drop(columns=[col for col in columns_to_drop if col in X_transformed_temp.columns], errors='ignore')

        return X_transformed_temp

    def transform(self, X):
        return self._get_transformed_columns(X)

    def get_feature_names_out(self, input_features=None):
        # This method provides the names of the features after transformation.
        # It relies on the feature_names_out_ stored during fit.
        if self.feature_names_out_ is not None:
            return self.feature_names_out_
        else:
            # Fallback if fit has not been called (less reliable but ensures the method exists)
            warnings.warn("`get_feature_names_out` called before `fit`. Column names might be incomplete or incorrect.")
            # This is a rough estimation of output columns, best to call fit first.
            initial_features = list(input_features) if input_features is not None else []

            new_features_static = [
                'selled_again', 'luxury_metric', 'sale_month', 'house_age_at_sale',
                'sqft_diff', 'lot_diff', 'bath_bed', 'mean_price_zip', 'geocluster'
            ]
            for office in self.seattle_offices:
                new_features_static.append(f'distance_to_{office["company"]}')
            new_features_static.extend(['distance_to_water', 'min_distance_to_downtown'])

            dropped_cols = [
                "id", "date", "sqft_living", "sqft_living15", "sqft_lot", "sqft_lot15",
                "bathrooms", "bedrooms", "view", "condition", "grade",
                "yr_built", "yr_renovated", "lat", "long", "sale_year"
            ]

            final_features = sorted(list(set([f for f in initial_features if f not in dropped_cols] + new_features_static)))
            return final_features


# =========================
# Load Data
# =========================
housing = pd.read_csv(
    "https://raw.githubusercontent.com/byui-cse/cse450-course/master/data/housing.csv"
)

# =========================
# Initial Data Filtering (applied directly to housing as per plan)
# These filters affect the number of rows and are applied before train-test split.
# =========================
housing = housing[housing['bathrooms'] < 3].copy()
housing = housing.drop_duplicates(subset=['id']).copy()
housing = housing[(housing['bedrooms'] > 0) & (housing['bathrooms'] > 0)].copy()

# =========================
# Define X and y (before log transformation of y)
# =========================
X = housing.drop(columns=['price'])
y = housing['price']

# =========================
# Train-Test Split
# =========================
X_train, X_test, y_train_original, y_test_original = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Apply log transformation to y
y_train = np.log1p(y_train_original)
y_test = np.log1p(y_test_original)

# =========================
# Instantiate and fit HousingFeatureEngineer to determine feature names
# =========================
feature_engineer_temp = HousingFeatureEngineer()
X_train_transformed_sample = feature_engineer_temp.fit_transform(X_train, y_train)

# =========================
# Determine numerical and categorical features based on transformed data
# =========================
numerical_features = X_train_transformed_sample.select_dtypes(include=np.number).columns.tolist()
categorical_features = ['zipcode'] # Zipcode is explicitly categorical for OneHotEncoding

# Ensure zipcode is treated as categorical if it's currently numerical
if 'zipcode' in numerical_features:
    numerical_features.remove('zipcode')

# =========================
# Define preprocessing steps with ColumnTransformer
# =========================
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore', drop='first'), categorical_features)
    ],
    remainder='passthrough' # Keep other columns that might not be in numerical/categorical lists
)

# =========================
# Reconstruct the Pipeline
# =========================
pipeline = Pipeline(steps=[
    ('feature_engineer', HousingFeatureEngineer()), # First step: custom feature engineering
    ('preprocessor', preprocessor), # Second step: scaling and one-hot encoding
    ("model", XGBRegressor(
        n_estimators=5000,
        learning_rate=0.02,
        max_depth=5,
        subsample=0.8,
        colsample_bytree=0.8,
        random_state=42,
        n_jobs=-1 # Use all available cores
    ))
])

# =========================
# Train the Pipeline
# =========================
pipeline.fit(X_train, y_train) # y_train is already log-transformed here

# =========================
# Evaluate
# =========================
y_pred_log = pipeline.predict(X_test)
y_pred = np.expm1(y_pred_log) # Inverse transform to get actual price scale

rmse = np.sqrt(mean_squared_error(y_test_original, y_pred)) # RMSE on original price scale
r2 = r2_score(y_test, y_pred_log) # R2 is typically reported on the transformed scale

print(f"RMSE: {rmse:.4f}")
print(f"R²: {r2:.4f}")

# =========================
# Feature Importances (from the XGBoost model within the pipeline)
# =========================
model = pipeline.named_steps["model"]

# Get feature names after preprocessing, including one-hot encoded ones
# We need to use the `get_feature_names_out` from the preprocessor to correctly map importances
preprocessor_output_features = pipeline.named_steps['preprocessor'].get_feature_names_out()

importance_df = pd.DataFrame({
    "Feature": preprocessor_output_features,
    "Importance": model.feature_importances_
}).sort_values(by="Importance", ascending=False)

print("\nTop 10 Feature Importances:")
print(importance_df.head(10))

/tmp/ipython-input-3194382465.py:144: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_transformed_temp['bath_bed'].fillna(0, inplace=True)
/tmp/ipython-input-3194382465.py:149: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_transformed_temp['mean_price_zip'].fillna(self.overall_mean_log_price_, inplace=True)
/tmp/ipython-input-3194382465.py:144: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_transformed_temp['bath_bed'].fillna(0, inplace=True)
/tmp/ipython-input-3194382465.py:149: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_transformed_temp['mean_price_zip'].fillna(self.overall_mean_log_price_, inplace=True)
/tmp/ipython-input-3194382465.py:144: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_transformed_temp['bath_bed'].fillna(0, inplace=True)
/tmp/ipython-input-3194382465.py:149: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_transformed_temp['mean_price_zip'].fillna(self.overall_mean_log_price_, inplace=True)
/tmp/ipython-input-3194382465.py:144: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_transformed_temp['bath_bed'].fillna(0, inplace=True)
/tmp/ipython-input-3194382465.py:149: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_transformed_temp['mean_price_zip'].fillna(self.overall_mean_log_price_, inplace=True)
/tmp/ipython-input-3194382465.py:144: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_transformed_temp['bath_bed'].fillna(0, inplace=True)
/tmp/ipython-input-3194382465.py:149: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_transformed_temp['mean_price_zip'].fillna(self.overall_mean_log_price_, inplace=True)

RMSE: 85235.6641
R²: 0.8825

Top 10 Feature Importances:
                             Feature  Importance
95         remainder__mean_price_zip    0.452643
90          remainder__luxury_metric    0.081690
71            remainder__sqft_living    0.059969
74             remainder__waterfront    0.055047
77                    remainder__lat    0.034908
82  remainder__distance_to_Starbucks    0.015703
79          remainder__sqft_living15    0.012075
75             remainder__sqft_above    0.012009
88      remainder__distance_to_water    0.011803
83  remainder__distance_to_Microsoft    0.010661

In [ ]:
results_df = pd.DataFrame({
    'Actual Price': np.expm1(y_test),
    'Predicted Price': np.expm1(y_pred_log)
})

# Create a scatter plot of Actual vs. Predicted Prices
p = ggplot(results_df, aes(x='Actual Price', y='Predicted Price')) + \
    geom_point(alpha=0.5) + \
    geom_abline(intercept=0, slope=1, color='red', linetype='dashed') + \
    labs(title='Actual vs. Predicted Housing Prices') + \
    xlab('Actual Price') + \
    ylab('Predicted Price')

p.show()

In [ ]:
# =========================
# Process holdout_mini and predict
# =========================
holdout_mini = pd.read_csv(
    "https://raw.githubusercontent.com/byui-cse/cse450-course/master/data/housing_holdout_test_mini.csv"
)

# The pipeline handles all feature engineering and preprocessing
holdout_preds_log = pipeline.predict(holdout_mini)
holdout_preds = np.expm1(holdout_preds_log) # Inverse transform to get actual price scale

# Create submission DataFrame, ensuring 'id' from the filtered holdout is used
submission = pd.DataFrame({
    "price": holdout_preds
})

# Save predictions to CSV
submission.to_csv("team44-module3-predictions.csv", index=False)

Predictions for holdout_mini saved to team44-module3-predictions.csv
Submission file shape: (81, 1)

/tmp/ipython-input-3194382465.py:144: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_transformed_temp['bath_bed'].fillna(0, inplace=True)
/tmp/ipython-input-3194382465.py:149: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_transformed_temp['mean_price_zip'].fillna(self.overall_mean_log_price_, inplace=True)

In [ ]:
# Task
import pandas as pd
import numpy as np
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from xgboost import XGBRegressor
from geopy.distance import great_circle
from sklearn.cluster import KMeans
import warnings

# Suppress SettingWithCopyWarning for chained assignments where copies are intentionally made
pd.options.mode.chained_assignment = None

# Define the distance calculation function
def calculate_distance(lat1, lon1, lat2, lon2):
    return great_circle((lat1, lon1), (lat2, lon2)).km

class HousingFeatureEngineer(BaseEstimator, TransformerMixin):
    def __init__(self):
        # Define constants used in feature engineering (like office locations, water bodies, downtowns)
        self.seattle_offices = [
            {"name": "Amazon HQ - Doppler Building", "company": "Amazon", "latitude": 47.615257, "longitude": -122.338356},
            {"name": "Starbucks Headquarters", "company": "Starbucks", "latitude": 47.618064, "longitude": -122.303796},
            {"name": "Microsoft Headquarters", "company": "Microsoft", "latitude": 47.643543, "longitude": -122.130821},
            {"name": "Google Seattle Campus (South Lake Union)", "company": "Google", "latitude": 47.622900, "longitude": -122.336600},
            {"name": "Meta (Facebook) Seattle Office", "company": "Meta", "latitude": 47.623500, "longitude": -122.336500},
            {"name": "Zillow Headquarters", "company": "Zillow", "latitude": 47.620500, "longitude": -122.338000},
            {"name": "Expedia Group Headquarters (Bellevue)", "company": "Expedia", "latitude": 47.610100, "longitude": -122.201500}
        ]

        self.seattle_water_bodies = [
            {"name": "Lake Union", "latitude": 47.6401, "longitude": -122.3366},
            {"name": "Lake Washington", "latitude": 47.6099, "longitude": -122.2155},
            {"name": "Puget Sound", "latitude": 47.6062, "longitude": -122.6035},
            {"name": "Green Lake", "latitude": 47.6749, "longitude": -122.3364},
            {"name": "Mercer Slough", "latitude": 47.5750, "longitude": -122.1950},
            {"name": "Elliott Bay", "latitude": 47.6111, "longitude": -122.3450}
        ]

        self.seattle_downtowns = [
            {"name": "Downtown Core", "latitude": 47.6097, "longitude": -122.3331},
            {"name": "Pioneer Square", "latitude": 47.6022, "longitude": -122.3332},
            {"name": "South Lake Union", "latitude": 47.6222, "longitude": -122.3364}
        ]
        self.mean_prices_by_zip_ = None
        self.kmeans_model_for_geocluster_ = None
        self.overall_mean_log_price_ = None
        self.feature_names_out_ = None # Store output feature names for get_feature_names_out

    def fit(self, X, y=None):
        if y is None:
            raise ValueError("y (original 'price' column) must be provided to the fit method for mean_price_zip calculation.")

        X_copy = X.copy()
        y_copy = y.copy()

        # Log transform y to calculate mean_price_zip
        y_log = np.log1p(y_copy)

        # Calculate mean_price_zip using log_price from training data
        temp_df = X_copy[['zipcode']].copy()
        temp_df['log_price_target'] = y_log
        self.mean_prices_by_zip_ = temp_df.groupby('zipcode')['log_price_target'].mean().rename('mean_price_zip').reset_index()
        self.overall_mean_log_price_ = self.mean_prices_by_zip_['mean_price_zip'].mean()

        # Fit KMeans for geocluster on training data
        self.kmeans_model_for_geocluster_ = KMeans(n_clusters=10, random_state=0, n_init='auto')
        self.kmeans_model_for_geocluster_.fit(X_copy[['lat', 'long']])

        # To get feature_names_out, transform a sample of X and store its columns
        self.feature_names_out_ = self._get_transformed_columns(X_copy).columns.tolist()

        return self

    def _get_transformed_columns(self, X_data):
        # Helper method to apply transformations and get column names
        X_transformed_temp = X_data.copy()

        # --- Add 'selled_again' feature ---
        id_counts = X_transformed_temp['id'].value_counts()
        # --- Add distance-to-office features ---
        for office in self.seattle_offices:
            company_name = office['company']
            office_lat = office['latitude']
            office_long = office['longitude']
            X_transformed_temp[f'distance_to_{company_name}'] = X_transformed_temp.apply(
                lambda row: calculate_distance(row['lat'], row['long'], office_lat, office_long),
                axis=1
            )

        # --- Add distance_to_water (min distance to any water body) ---
        min_distances_to_water = []
        for index, row in X_transformed_temp.iterrows():
            house_lat = row['lat']
            house_long = row['long']
            distances_to_all_water_bodies = []
            for water_body in self.seattle_water_bodies:
                water_lat = water_body['latitude']
                water_long = water_body['longitude']
                distance = calculate_distance(house_lat, house_long, water_lat, water_long)
                distances_to_all_water_bodies.append(distance)
            min_distances_to_water.append(min(distances_to_all_water_bodies))
        X_transformed_temp['distance_to_water'] = min_distances_to_water

        # --- Add min_distance_to_downtown ---
        min_distances_to_downtown = []
        for index, row in X_transformed_temp.iterrows():
            house_lat = row['lat']
            house_long = row['long']
            distances_to_all_downtowns = []
            for downtown_location in self.seattle_downtowns:
                downtown_lat = downtown_location['latitude']
                downtown_long = downtown_location['longitude']
                distance = calculate_distance(house_lat, house_long, downtown_lat, downtown_long)
                distances_to_all_downtowns.append(distance)
            min_distances_to_downtown.append(min(distances_to_all_downtowns))
        X_transformed_temp['min_distance_to_downtown'] = min_distances_to_downtown

        # --- Add 'luxury_metric' feature ---
        X_transformed_temp['luxury_metric'] = X_transformed_temp['view'] + X_transformed_temp['grade'] + X_transformed_temp['condition']

        # --- Date-based features ('year', 'sale_month', 'house_age_at_sale') ---
        if 'date' in X_transformed_temp.columns:
            if not pd.api.types.is_datetime64_any_dtype(X_transformed_temp['date']):
                X_transformed_temp['date'] = pd.to_datetime(X_transformed_temp['date'], format='%Y%m%dT%H%M%S')
            X_transformed_temp['sale_year'] = X_transformed_temp['date'].dt.year
            X_transformed_temp['sale_month'] = X_transformed_temp['date'].dt.month
            X_transformed_temp['house_age_at_sale'] = X_transformed_temp['sale_year'] - X_transformed_temp['yr_built']
        else:
            X_transformed_temp['sale_year'] = 0
            X_transformed_temp['sale_month'] = 0
            X_transformed_temp['house_age_at_sale'] = 0

        # --- Add 'sqft_diff' and 'lot_diff' ---
        X_transformed_temp['sqft_diff'] = X_transformed_temp['sqft_living'] - X_transformed_temp['sqft_living15']
        X_transformed_temp['lot_diff'] = X_transformed_temp['sqft_lot'] - X_transformed_temp['sqft_lot15']

        # --- Add 'bath_bed' ---
        X_transformed_temp['bath_bed'] = X_transformed_temp['bathrooms'] / X_transformed_temp['bedrooms'].replace(0, np.nan)
        X_transformed_temp['bath_bed'].fillna(0, inplace=True)

        # --- Add 'mean_price_zip' ---
        if self.mean_prices_by_zip_ is not None:
            X_transformed_temp = X_transformed_temp.merge(self.mean_prices_by_zip_, on='zipcode', how='left')
            X_transformed_temp['mean_price_zip'].fillna(self.overall_mean_log_price_, inplace=True)

        # --- Add 'geocluster' ---
        if self.kmeans_model_for_geocluster_ is not None and 'lat' in X_transformed_temp.columns and 'long' in X_transformed_temp.columns:
            X_transformed_temp['geocluster'] = self.kmeans_model_for_geocluster_.predict(X_transformed_temp[['lat', 'long']])

        # Define columns to drop after feature engineering
        columns_to_drop = [
            "id", "date", # Identifiers, original date
            "view", "condition", "grade",# now part of 'luxury_metric'
            'bath_bed',
            "yr_built", "yr_renovated", # Replaced by house_age_at_sale or less important
            "sale_year", # Derived from 'date', potentially redundant with 'house_age_at_sale'
        ]

        X_transformed_temp = X_transformed_temp.drop(columns=[col for col in columns_to_drop if col in X_transformed_temp.columns], errors='ignore')

        return X_transformed_temp

    def transform(self, X):
        return self._get_transformed_columns(X)

    def get_feature_names_out(self, input_features=None):
        # This method provides the names of the features after transformation.
        # It relies on the feature_names_out_ stored during fit.
        if self.feature_names_out_ is not None:
            return self.feature_names_out_
        else:
            # Fallback if fit has not been called (less reliable but ensures the method exists)
            warnings.warn("`get_feature_names_out` called before `fit`. Column names might be incomplete or incorrect.")
            # This is a rough estimation of output columns, best to call fit first.
            initial_features = list(input_features) if input_features is not None else []

            new_features_static = [
                'selled_again', 'luxury_metric', 'sale_month', 'house_age_at_sale',
                'sqft_diff', 'lot_diff', 'bath_bed', 'mean_price_zip', 'geocluster'
            ]
            for office in self.seattle_offices:
                new_features_static.append(f'distance_to_{office["company"]}')
            new_features_static.extend(['distance_to_water', 'min_distance_to_downtown'])

            dropped_cols = [
                "id", "date", "sqft_living", "sqft_living15", "sqft_lot", "sqft_lot15",
                "bathrooms", "bedrooms", "view", "condition", "grade",
                "yr_built", "yr_renovated", "lat", "long", "sale_year"
            ]

            final_features = sorted(list(set([f for f in initial_features if f not in dropped_cols] + new_features_static)))
            return final_features


# =========================
# Load Data
# =========================
housing = pd.read_csv(
    "https://raw.githubusercontent.com/byui-cse/cse450-course/master/data/housing.csv"
)

# =========================
# Initial Data Filtering (applied directly to housing as per plan)
# These filters affect the number of rows and are applied before train-test split.
# =========================
housing = housing[housing['bathrooms'] < 3].copy()
housing = housing.drop_duplicates(subset=['id']).copy()
housing = housing[(housing['bedrooms'] > 0) & (housing['bathrooms'] > 0)].copy()

# =========================
# Define X and y (before log transformation of y)
# =========================
X = housing.drop(columns=['price'])
y = housing['price']

# =========================
# Train-Test Split
# =========================
X_train, X_test, y_train_original, y_test_original = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Apply log transformation to y
y_train = np.log1p(y_train_original)
y_test = np.log1p(y_test_original)

# =========================
# Instantiate and fit HousingFeatureEngineer to determine feature names
# =========================
feature_engineer_temp = HousingFeatureEngineer()
X_train_transformed_sample = feature_engineer_temp.fit_transform(X_train, y_train)

# =========================
# Determine numerical and categorical features based on transformed data
# =========================
numerical_features = X_train_transformed_sample.select_dtypes(include=np.number).columns.tolist()
categorical_features = ['zipcode'] # Zipcode is explicitly categorical for OneHotEncoding

# Ensure zipcode is treated as categorical if it's currently numerical
if 'zipcode' in numerical_features:
    numerical_features.remove('zipcode')

# =========================
# Define preprocessing steps with ColumnTransformer
# =========================
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore', drop='first'), categorical_features)
    ],
    remainder='passthrough' # Keep other columns that might not be in numerical/categorical lists
)

# =========================
# Reconstruct the Pipeline
# =========================
pipeline = Pipeline(steps=[
    ('feature_engineer', HousingFeatureEngineer()), # First step: custom feature engineering
    ('preprocessor', preprocessor), # Second step: scaling and one-hot encoding
    ("model", XGBRegressor(
        n_estimators=5000,
        learning_rate=0.02,
        max_depth=5,
        subsample=0.8,
        colsample_bytree=0.8,
        random_state=42,
        n_jobs=-1 # Use all available cores
    ))
])

# =========================
# Train the Pipeline
# =========================
pipeline.fit(X_train, y_train) # y_train is already log-transformed here

# =========================
# Evaluate
# =========================
y_pred_log = pipeline.predict(X_test)
y_pred = np.expm1(y_pred_log) # Inverse transform to get actual price scale

rmse = np.sqrt(mean_squared_error(y_test_original, y_pred)) # RMSE on original price scale
r2 = r2_score(y_test, y_pred_log) # R2 is typically reported on the transformed scale

print(f"RMSE: {rmse:.4f}")
print(f"R²: {r2:.4f}")

# =========================
# Feature Importances (from the XGBoost model within the pipeline)
# =========================
model = pipeline.named_steps["model"]

# Get feature names after preprocessing, including one-hot encoded ones
# We need to use the `get_feature_names_out` from the preprocessor to correctly map importances
preprocessor_output_features = pipeline.named_steps['preprocessor'].get_feature_names_out()

importance_df = pd.DataFrame({
    "Feature": preprocessor_output_features,
    "Importance": model.feature_importances_
}).sort_values(by="Importance", ascending=False)

print("\nTop 10 Feature Importances:")
print(importance_df.head(10))

/tmp/ipython-input-3194382465.py:144: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_transformed_temp['bath_bed'].fillna(0, inplace=True)
/tmp/ipython-input-3194382465.py:149: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_transformed_temp['mean_price_zip'].fillna(self.overall_mean_log_price_, inplace=True)
/tmp/ipython-input-3194382465.py:144: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_transformed_temp['bath_bed'].fillna(0, inplace=True)
/tmp/ipython-input-3194382465.py:149: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_transformed_temp['mean_price_zip'].fillna(self.overall_mean_log_price_, inplace=True)
/tmp/ipython-input-3194382465.py:144: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_transformed_temp['bath_bed'].fillna(0, inplace=True)
/tmp/ipython-input-3194382465.py:149: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_transformed_temp['mean_price_zip'].fillna(self.overall_mean_log_price_, inplace=True)
/tmp/ipython-input-3194382465.py:144: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_transformed_temp['bath_bed'].fillna(0, inplace=True)
/tmp/ipython-input-3194382465.py:149: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_transformed_temp['mean_price_zip'].fillna(self.overall_mean_log_price_, inplace=True)
/tmp/ipython-input-3194382465.py:144: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_transformed_temp['bath_bed'].fillna(0, inplace=True)
/tmp/ipython-input-3194382465.py:149: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_transformed_temp['mean_price_zip'].fillna(self.overall_mean_log_price_, inplace=True)

RMSE: 85235.6641
R²: 0.8825

Top 10 Feature Importances:
                             Feature  Importance
95         remainder__mean_price_zip    0.452643
90          remainder__luxury_metric    0.081690
71            remainder__sqft_living    0.059969
74             remainder__waterfront    0.055047
77                    remainder__lat    0.034908
82  remainder__distance_to_Starbucks    0.015703
79          remainder__sqft_living15    0.012075
75             remainder__sqft_above    0.012009
88      remainder__distance_to_water    0.011803
83  remainder__distance_to_Microsoft    0.010661

Removing places

In [ ]:
import pandas as pd
import numpy as np
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from xgboost import XGBRegressor
import warnings

# Suppress SettingWithCopyWarning for chained assignments where copies are intentionally made
pd.options.mode.chained_assignment = None

class HousingFeatureEngineer(BaseEstimator, TransformerMixin):
    def __init__(self):
        # Removed all location-based attributes
        self.mean_prices_by_zip_ = None
        self.overall_mean_log_price_ = None
        self.feature_names_out_ = None # Store output feature names for get_feature_names_out

    def fit(self, X, y=None):
        if y is None:
            raise ValueError("y (original 'price' column) must be provided to the fit method for mean_price_zip calculation.")

        X_copy = X.copy()
        y_copy = y.copy()

        # Log transform y to calculate mean_price_zip
        y_log = np.log1p(y_copy)

        # Calculate mean_price_zip using log_price from training data
        temp_df = X_copy[['zipcode']].copy()
        temp_df['log_price_target'] = y_log
        self.mean_prices_by_zip_ = temp_df.groupby('zipcode')['log_price_target'].mean().rename('mean_price_zip').reset_index()
        self.overall_mean_log_price_ = self.mean_prices_by_zip_['mean_price_zip'].mean()

        # Removed KMeans fitting for geocluster

        # To get feature_names_out, transform a sample of X and store its columns
        self.feature_names_out_ = self._get_transformed_columns(X_copy).columns.tolist()

        return self

    def _get_transformed_columns(self, X_data):
        # Helper method to apply transformations and get column names
        X_transformed_temp = X_data.copy()

        # Removed 'selled_again' feature as it wasn't implemented/used in the previous version effectively

        # Removed distance-to-office features

        # Removed distance_to_water

        # Removed min_distance_to_downtown

        # --- Add 'luxury_metric' feature ---
        X_transformed_temp['luxury_metric'] = X_transformed_temp['view'] + X_transformed_temp['grade'] + X_transformed_temp['condition']

        # --- Date-based features ('year', 'sale_month', 'house_age_at_sale') ---
        if 'date' in X_transformed_temp.columns:
            if not pd.api.types.is_datetime64_any_dtype(X_transformed_temp['date']):
                X_transformed_temp['date'] = pd.to_datetime(X_transformed_temp['date'], format='%Y%m%dT%H%M%S')
            X_transformed_temp['sale_year'] = X_transformed_temp['date'].dt.year
            X_transformed_temp['sale_month'] = X_transformed_temp['date'].dt.month
            X_transformed_temp['house_age_at_sale'] = X_transformed_temp['sale_year'] - X_transformed_temp['yr_built']
        else:
            # Handle cases where 'date' might be missing in some datasets (e.g., holdout_mini might not have 'date' in same format)
            # For this subtask, we assume 'date' is present or handled upstream for these calculations
            X_transformed_temp['sale_year'] = 0 # Placeholder
            X_transformed_temp['sale_month'] = 0 # Placeholder
            X_transformed_temp['house_age_at_sale'] = 0 # Placeholder

        # --- Add 'sqft_diff' and 'lot_diff' ---
        X_transformed_temp['sqft_diff'] = X_transformed_temp['sqft_living'] - X_transformed_temp['sqft_living15']
        X_transformed_temp['lot_diff'] = X_transformed_temp['sqft_lot'] - X_transformed_temp['sqft_lot15']

        # --- Add 'bath_bed' ---
        X_transformed_temp['bath_bed'] = X_transformed_temp['bathrooms'] / X_transformed_temp['bedrooms'].replace(0, np.nan)
        X_transformed_temp['bath_bed'] = X_transformed_temp['bath_bed'].fillna(0) # Fix: removed inplace=True

        # --- Add 'mean_price_zip' ---
        if self.mean_prices_by_zip_ is not None:
            X_transformed_temp = X_transformed_temp.merge(self.mean_prices_by_zip_, on='zipcode', how='left')
            X_transformed_temp['mean_price_zip'] = X_transformed_temp['mean_price_zip'].fillna(self.overall_mean_log_price_) # Fix: removed inplace=True

        # Removed 'geocluster' creation

        # Define columns to drop after feature engineering
        columns_to_drop = [
            "id", "date", # Identifiers, original date
            "view", "condition", "grade",# now part of 'luxury_metric'
            "yr_built", "yr_renovated", # Replaced by house_age_at_sale or less important
            "sale_year", # Derived from 'date', potentially redundant with 'house_age_at_sale'
            'lat', 'long', # No longer used for location-based features
            'zipcode' # User does not want to use zipcode
        ]

        X_transformed_temp = X_transformed_temp.drop(columns=[col for col in columns_to_drop if col in X_transformed_temp.columns], errors='ignore')

        return X_transformed_temp

    def transform(self, X):
        return self._get_transformed_columns(X)

    def get_feature_names_out(self, input_features=None):
        # This method provides the names of the features after transformation.
        # It relies on the feature_names_out_ stored during fit.
        if self.feature_names_out_ is not None:
            return self.feature_names_out_
        else:
            # Fallback if fit has not been called (less reliable but ensures the method exists)
            warnings.warn("`get_feature_names_out` called before `fit`. Column names might be incomplete or incorrect.")
            # This is a rough estimation of output columns, best to call fit first.
            initial_features = list(input_features) if input_features is not None else []

            new_features_static = [
                'luxury_metric', 'sale_month', 'house_age_at_sale',
                'sqft_diff', 'lot_diff', 'bath_bed', 'mean_price_zip'
            ]
            # Removed addition of distance-to-office features
            # Removed addition of distance_to_water, min_distance_to_downtown, geocluster

            # This list should reflect what is actually dropped by _get_transformed_columns
            dropped_cols = [
                "id", "date",
                "view", "condition", "grade",
                "yr_built", "yr_renovated",
                "sale_year",
                "lat", "long",
                "zipcode" # Added zipcode to dropped_cols
            ]

            final_features = sorted(list(set([f for f in initial_features if f not in dropped_cols] + new_features_static)))
            return final_features


# =========================
# Load Data
# =========================
housing = pd.read_csv(
    "https://raw.githubusercontent.com/byui-cse/cse450-course/master/data/housing.csv"
)

# =========================
# Initial Data Filtering (applied directly to housing as per plan)
# These filters affect the number of rows and are applied before train-test split.
# =========================
housing = housing[housing['bathrooms'] < 3].copy()
housing = housing.drop_duplicates(subset=['id']).copy()
housing = housing[(housing['bedrooms'] > 0) & (housing['bathrooms'] > 0)].copy()

# =========================
# Define X and y (before log transformation of y)
# =========================
X = housing.drop(columns=['price'])
y = housing['price']

# =========================
# Train-Test Split
# =========================
X_train, X_test, y_train_original, y_test_original = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Apply log transformation to y
y_train = np.log1p(y_train_original)
y_test = np.log1p(y_test_original)

# =========================
# Instantiate and fit HousingFeatureEngineer to determine feature names
# =========================
feature_engineer_temp = HousingFeatureEngineer()
X_train_transformed_sample = feature_engineer_temp.fit_transform(X_train, y_train)

# =========================
# Determine numerical and categorical features based on transformed data
# =========================
numerical_features = X_train_transformed_sample.select_dtypes(include=np.number).columns.tolist()
categorical_features = [] # User does not want to use zipcode or one-hot encode it.

# Ensure zipcode is treated as categorical if it's currently numerical
if 'zipcode' in numerical_features:
    numerical_features.remove('zipcode') # Zipcode will be dropped by FeatureEngineer, so no need to remove here, but for safety

# =========================
# Define preprocessing steps with ColumnTransformer
# =========================
transformers_list = []

# Add numerical features scaling
if numerical_features:
    transformers_list.append(('num', StandardScaler(), numerical_features))

# Add categorical features (will be empty based on user request)
if categorical_features:
    transformers_list.append(('cat', OneHotEncoder(handle_unknown='ignore', drop='first'), categorical_features))

preprocessor = ColumnTransformer(
    transformers=transformers_list,
    remainder='passthrough' # Keep other columns that might not be in numerical/categorical lists
)

# =========================
# Reconstruct the Pipeline
# =========================
pipeline = Pipeline(steps=[
    ('feature_engineer', HousingFeatureEngineer()), # First step: custom feature engineering
    ('preprocessor', preprocessor), # Second step: scaling and one-hot encoding
    ("model", XGBRegressor(
        n_estimators=5000,
        learning_rate=0.02,
        max_depth=5,
        subsample=0.8,
        colsample_bytree=0.8,
        random_state=42,
        n_jobs=-1 # Use all available cores
    ))
])

# =========================
# Train the Pipeline
# =========================
pipeline.fit(X_train, y_train) # y_train is already log-transformed here

# =========================
# Evaluate
# =========================
y_pred_log = pipeline.predict(X_test)
y_pred = np.expm1(y_pred_log) # Inverse transform to get actual price scale

rmse = np.sqrt(mean_squared_error(y_test_original, y_pred)) # RMSE on original price scale
r2 = r2_score(y_test, y_pred_log) # R2 is typically reported on the transformed scale

print(f"RMSE: {rmse:.4f}")
print(f"R²: {r2:.4f}")

# =========================
# Feature Importances (from the XGBoost model within the pipeline)
# =========================
model = pipeline.named_steps["model"]

# Get feature names after preprocessing, including one-hot encoded ones
# The ColumnTransformer's get_feature_names_out method handles combining names from all transformers and remainders.
preprocessor_output_features = pipeline.named_steps['preprocessor'].get_feature_names_out()

importance_df = pd.DataFrame({
    "Feature": preprocessor_output_features,
    "Importance": model.feature_importances_
}).sort_values(by="Importance", ascending=False)

print("\nTop 10 Feature Importances:")
print(importance_df.head(10))

RMSE: 95962.6165
R²: 0.8568

Top 10 Feature Importances:
                   Feature  Importance
16     num__mean_price_zip    0.291347
10      num__luxury_metric    0.235081
5          num__waterfront    0.155979
2         num__sqft_living    0.126672
6          num__sqft_above    0.025811
8       num__sqft_living15    0.024104
12  num__house_age_at_sale    0.020677
9          num__sqft_lot15    0.017325
1           num__bathrooms    0.016802
3            num__sqft_lot    0.014461

In [ ]:
!pip install lets-plot

Collecting lets-plot
  Downloading lets_plot-4.8.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (12 kB)
Collecting pypng (from lets-plot)
  Downloading pypng-0.20220715.0-py3-none-any.whl.metadata (13 kB)
Collecting palettable (from lets-plot)
  Downloading palettable-3.3.3-py2.py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from lets-plot) (11.3.0)
Downloading lets_plot-4.8.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (6.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.8/6.8 MB 50.5 MB/s eta 0:00:00
Downloading palettable-3.3.3-py2.py3-none-any.whl (332 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 332.3/332.3 kB 23.6 MB/s eta 0:00:00
Downloading pypng-0.20220715.0-py3-none-any.whl (58 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.1/58.1 kB 3.6 MB/s eta 0:00:00
Installing collected packages: pypng, palettable, lets-plot
Successfully installed lets-plot-4.8.2 palettable-3.3.3 pypng-0.20220715.0

In [ ]:
from lets_plot import *
import numpy as np

# Create a DataFrame with actual and predicted prices
results_df = pd.DataFrame({
    'Actual Price': np.expm1(y_test),
    'Predicted Price': np.expm1(y_pred_log)
})

# Create a scatter plot of Actual vs. Predicted Prices
p = ggplot(results_df, aes(x='Actual Price', y='Predicted Price')) + \
    geom_point(alpha=0.5) + \
    geom_abline(intercept=0, slope=1, color='red', linetype='dashed') + \
    labs(title='Actual vs. Predicted Housing Prices') + \
    xlab('Actual Price') + \
    ylab('Predicted Price')

p.show()

two models trained and fussioned

# SPLIT TWO MODEL

In [364]:
import pandas as pd
import numpy as np
from geopy.distance import great_circle

housing = pd.read_csv(
    "https://raw.githubusercontent.com/byui-cse/cse450-course/master/data/housing.csv"
)

In [325]:
# from sklearn.neighbors import NearestNeighbors
# from geopy.distance import great_circle
# location_price_data = housing[['id', 'lat', 'long', 'price']].copy()
# nn_model = NearestNeighbors(n_neighbors=5, algorithm='ball_tree')

# nn_model.fit(location_price_data[['lat', 'long']])

# distances, indices = nn_model.kneighbors(location_price_data[['lat', 'long']])

# neighborhood_avg_prices = {}

# for i in range(len(location_price_data)):

#     neighbor_indices = indices[i, 1:]


#     neighbor_prices = location_price_data.iloc[neighbor_indices]['price']

#     if not neighbor_prices.empty:
#         avg_price = neighbor_prices.mean()
#     else:
#         avg_price = location_price_data.iloc[i]['price']

#     house_id = location_price_data.iloc[i]['id']
#     neighborhood_avg_prices[house_id] = avg_price

# neighborhood_avg_prices_df = pd.DataFrame.from_dict(neighborhood_avg_prices, orient='index', columns=['neighborhood_avg_price'])
# neighborhood_avg_prices_df = neighborhood_avg_prices_df.reset_index().rename(columns={'index': 'id'})
# neighborhood_avg_prices_df.head()

In [365]:
mean_price_dict_by_zipcode = housing.groupby('zipcode')['price'].mean().to_dict()

def rawtransformer(rawdf, mean_price_dict_by_zipcode):
  rawdf['date'] = pd.to_datetime(rawdf['date'], format='%Y%m%dT%H%M%S')
  rawdf['year'] = rawdf['date'].dt.year
  rawdf['sale_month'] = rawdf['date'].dt.month
  rawdf = rawdf.drop(columns='date')
  rawdf['luxury_metric'] = (rawdf['view'] + rawdf['condition']) * rawdf['grade'] + 10*rawdf['waterfront']
  rawdf = rawdf.drop(columns = ['view','condition','grade','waterfront'])
  rawdf['houseage'] = rawdf['year'] - rawdf['yr_built']
  rawdf['renovated_years'] = np.where((rawdf['yr_renovated']>0),(rawdf['year'] - rawdf['yr_renovated']),0)
  rawdf = rawdf.drop(columns = ['yr_built','yr_renovated','sale_month','sqft_basement'])
  rawdf['mean_prices_by_zip'] = rawdf['zipcode'].map(mean_price_dict_by_zipcode)

  seattle_offices = [
    {"company": "Amazon",    "latitude": 47.615257, "longitude": -122.338356},
    {"company": "Starbucks", "latitude": 47.618064, "longitude": -122.303796},
    {"company": "Microsoft", "latitude": 47.643543, "longitude": -122.130821},
    {"company": "Google",    "latitude": 47.622900, "longitude": -122.336600},
    {"company": "Meta",      "latitude": 47.623500, "longitude": -122.336500},
    {"company": "Zillow",    "latitude": 47.620500, "longitude": -122.338000},
    {"company": "Expedia",   "latitude": 47.610100, "longitude": -122.201500},
]

  def dist_km(lat1, lon1, lat2, lon2):
      return great_circle((lat1, lon1), (lat2, lon2)).km

  # --- Add distance-to-office features ---
  for office in seattle_offices:
      company = office["company"]
      lat2, lon2 = office["latitude"], office["longitude"]
      rawdf[f"distance_to_{company}"] = rawdf.apply(
          lambda row: dist_km(row["lat"], row["long"], lat2, lon2),
          axis=1
      )

  # --- Same water bodies list you used in training ---
  seattle_water_bodies = [
      {"name": "Lake Union",     "latitude": 47.6401, "longitude": -122.3366},
      {"name": "Lake Washington","latitude": 47.6099, "longitude": -122.2155},
      {"name": "Puget Sound",    "latitude": 47.6062, "longitude": -122.6035},
      {"name": "Green Lake",     "latitude": 47.6749, "longitude": -122.3364},
      {"name": "Mercer Slough",  "latitude": 47.5750, "longitude": -122.1950},
      {"name": "Elliott Bay",    "latitude": 47.6111, "longitude": -122.3450},
  ]

  # --- Add distance_to_water (min distance to any water body) ---
  rawdf["distance_to_water"] = rawdf.apply(
      lambda row: min(
          dist_km(row["lat"], row["long"], wb["latitude"], wb["longitude"])
          for wb in seattle_water_bodies
      ),
      axis=1
  )
  DOWNTOWN_SEATTLE_LAT = 47.6062
  DOWNTOWN_SEATTLE_LONG = -122.3321
  # --- Add distance to Downtown Seattle for holdout ---
  rawdf['distance_to_downtown_seattle'] = rawdf.apply(
      lambda row: dist_km(row['lat'], row['long'], DOWNTOWN_SEATTLE_LAT, DOWNTOWN_SEATTLE_LONG),
      axis=1
  )
  income_df = pd.read_csv("/content/transposed_income_by_zip.csv") # Corrected to load from local path
  rawdf = pd.merge(
            rawdf,
            income_df[['zipcode', 'number_of_houses', 'mean_income']],
            on='zipcode',
            how='left'
        )
  # rawdf = pd.merge(rawdf, neighborhood_avg_prices_df, on='id', how='left')
  return rawdf

In [366]:
housing = rawtransformer(housing, mean_price_dict_by_zipcode)
housing

,id,bedrooms,bathrooms,sqft_living,sqft_lot,floors,sqft_above,zipcode,lat,long,...,distance_to_Starbucks,distance_to_Microsoft,distance_to_Google,distance_to_Meta,distance_to_Zillow,distance_to_Expedia,distance_to_water,distance_to_downtown_seattle,number_of_houses,mean_income
0,1565930130,4,3.25,3760,4675,2.0,2740,98038,47.3862,-122.048,...,32.154939,29.283467,34.098184,34.144862,33.960297,27.437538,23.722765,32.465194,12012,107851
1,3279000420,3,1.75,1460,7800,1.0,1040,98023,47.3035,-122.382,...,35.468629,42.262025,35.679317,35.746446,35.403701,36.694076,33.304676,33.867206,17560,86045
2,194000575,4,1.00,1340,5800,1.5,1340,98116,47.5658,-122.389,...,8.637088,21.198954,7.466757,7.527478,7.184813,14.899650,6.021751,6.196107,11541,103895
3,2115510160,3,1.75,1440,8050,1.0,1440,98023,47.3187,-122.390,...,33.912602,41.037496,34.062847,34.129983,33.785528,35.365193,32.050455,32.263544,17560,86045
4,7522500005,2,1.50,1780,4750,1.0,1080,98117,47.6859,-122.395,...,10.176836,20.336301,8.258809,8.206278,8.432828,16.767527,4.554341,10.037065,13813,108574
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,5272200045,3,1.50,1000,6914,1.0,1000,98125,47.7144,-122.319,...,10.772425,16.141702,10.259350,10.192223,10.537708,14.558074,4.581200,12.071243,17836,77284
19996,9578500790,3,2.50,3087,5002,2.0,3087,98023,47.2974,-122.349,...,35.817858,41.837398,36.206003,36.272892,35.936648,36.496507,32.969385,34.360547,17560,86045
19997,7202350480,3,2.50,2120,4780,2.0,2120,98053,47.6810,-122.032,...,21.528866,8.492212,23.712948,23.687520,23.888149,14.946220,15.858001,23.971642,7876,152901
19998,1723049033,1,0.75,380,15000,1.0,380,98168,47.4810,-122.323,...,15.308841,23.121390,15.811559,15.877656,15.552510,17.007005,14.199066,13.938371,11522,62468
19999,6147650280,4,2.50,3130,5999,2.0,3130,98042,47.3837,-122.099,...,30.262369,28.991931,32.031124,32.082312,31.869227,26.325957,22.461783,30.311795,15784,102333

In [367]:
from sklearn.model_selection import train_test_split
x = housing.drop(columns=['price','id','floors','renovated_years'])
y = housing['price']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=67)

In [351]:
from sklearn.model_selection import RandomizedSearchCV
from xgboost import XGBRegressor

model = XGBRegressor()
param_grid = {
    "max_depth": [3, 4, 5],
    "learning_rate": [0.01, 0.05, 0.1, 0.2],
    "n_estimators": [100, 200, 300, 400, 500],
    "subsample": [0.8, 1.0],
}
random = RandomizedSearchCV(
    model,
    param_distributions=param_grid,
    n_iter=20,
    cv=5,
    scoring="r2", # Changed scoring metric to R^2
    random_state=42
)

random.fit(x_train, y_train)
print(random.best_params_)

{'subsample': 1.0, 'n_estimators': 500, 'max_depth': 5, 'learning_rate': 0.1}

In [368]:
from xgboost import XGBRegressor
model = XGBRegressor(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=5,
    subsample=0.8,
    )
model.fit(x_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=500,
             n_jobs=None, num_parallel_tree=None, ...)

In [369]:
# !pip install lets-plot
from sklearn.metrics import root_mean_squared_error, r2_score
from lets_plot import *
y_preds = model.predict(x_test)

print(f"RMSE: {root_mean_squared_error(y_test,y_preds)}")
print(f'R2: {r2_score(y_test, y_preds)}')

# Get feature importances
feature_importances = model.feature_importances_
feature_names = x_train.columns

# Create a DataFrame for better visualization
importance_df = pd.DataFrame({
    'feature': feature_names,
    'importance': feature_importances
}).sort_values(by='importance', ascending=False)

# Print feature importances
print(f'Feature Importance')
print(importance_df)

# Plot feature importances
p = ggplot(importance_df, aes(x='feature', y='importance')) + \
    geom_bar(stat='identity', fill='steelblue') + \
    coord_flip() + \
    labs(x='Feature', y='Importance', title='Feature Importances from XGBoost Model')
p.show()

RMSE: 123180.50836798295
R2: 0.8926283401574492
Feature Importance
                         feature  importance
13            mean_prices_by_zip    0.282526
2                    sqft_living    0.230924
19            distance_to_Zillow    0.075536
11                 luxury_metric    0.073393
15         distance_to_Starbucks    0.066486
4                     sqft_above    0.028966
14            distance_to_Amazon    0.027013
8                  sqft_living15    0.026021
17            distance_to_Google    0.021633
18              distance_to_Meta    0.017394
6                            lat    0.017392
1                      bathrooms    0.017314
22  distance_to_downtown_seattle    0.017157
21             distance_to_water    0.016259
7                           long    0.012027
10                          year    0.011068
16         distance_to_Microsoft    0.010310
20           distance_to_Expedia    0.009458
9                     sqft_lot15    0.007785
12                      houseage    0.007532
3                       sqft_lot    0.007377
5                        zipcode    0.004997
24                   mean_income    0.004293
23              number_of_houses    0.004075
0                       bedrooms    0.003065

In [370]:
results_df = pd.DataFrame({
    'Actual Price': y_test,
    'Predicted Price': y_preds
})

# Create a scatter plot of Actual vs. Predicted Prices
p = ggplot(results_df, aes(x='Actual Price', y='Predicted Price')) + \
    geom_point(alpha=0.5) + \
    geom_abline(intercept=0, slope=1, color='red', linetype='dashed') + \
    labs(title='Actual vs. Predicted Housing Prices') + \
    xlab('Actual Price') + \
    ylab('Predicted Price')

p.show()

HoldOuts

In [371]:
holdout_mini = pd.read_csv(
    "https://raw.githubusercontent.com/byui-cse/cse450-course/master/data/housing_holdout_test_mini.csv"
)
holdout_mini = rawtransformer(holdout_mini, mean_price_dict_by_zipcode)
holdout = pd.read_csv(
    "https://raw.githubusercontent.com/byui-cse/cse450-course/master/data/housing_holdout_test.csv"
)
holdout = rawtransformer(holdout, mean_price_dict_by_zipcode)

In [372]:
holdout_mini_preds = model.predict(holdout_mini.drop(columns=['id','floors','renovated_years']))
holdout_preds = model.predict(holdout.drop(columns=['id','floors','renovated_years']))

In [373]:
import numpy as np
import pandas as pd


holdout_mini_preds = pd.DataFrame({
    "predictions": holdout_mini_preds
})
holdout_mini_preds.to_csv("team8-module3-predictions.csv", index=False)

holdout_preds = pd.DataFrame({
    "predictions": holdout_preds
})
holdout_preds.to_csv("manolo-module3-predictions.csv", index=False)

# Graphs

In [ ]:
numerical_features_for_dist = [
    'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors',
    'sqft_above', 'sqft_basement', 'sqft_living15', 'sqft_lot15',
    'sale_month', 'luxury_metric', 'houseage', 'renovated_years',
    'sqft_diff', 'lot_diff', 'bath_bed', 'mean_price_zip', 'geocluster'
]

actual_numerical_features = [col for col in numerical_features_for_dist if col in housing.columns]

print(f"Features identified for distribution plots: {actual_numerical_features}")

Features identified for distribution plots: ['bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors', 'sqft_above', 'sqft_basement', 'sqft_living15', 'sqft_lot15', 'sale_month', 'luxury_metric', 'houseage', 'renovated_years']

In [ ]:
plots_distribution = []
for feature in actual_numerical_features:
    if feature in ['bedrooms', 'bathrooms', 'floors', 'sale_month', 'geocluster']:
        p = (
            ggplot(housing, aes(x=feature))
            + geom_histogram(binwidth=1, fill='steelblue', color='black')
            + labs(title=f'Distribution of {feature}', x=feature, y='Frequency')
        )
    else:
        p = (
            ggplot(housing, aes(x=feature))
            + geom_histogram(fill='steelblue', color='black')
            + labs(title=f'Distribution of {feature}', x=feature, y='Frequency')
        )
    plots_distribution.append(p)

if len(plots_distribution) > 0:
    print("--- Visualizing Feature Distributions ---")
    combined_distribution_plot = gggrid(plots_distribution, ncol=3)
    combined_distribution_plot.show()
else:
    print("No numerical features found for distribution plotting.")

--- Visualizing Feature Distributions ---

In [ ]:
features_for_scatter_vs_price = [
    'luxury_metric', 'sqft_living', 'lat', 'long', 'mean_price_zip_y', 'houseage'
]

scatter_plots_vs_price = []
# Ensure 'log_price' is available in the DataFrame for plotting against
if 'log_price' not in housing.columns:
    # Assuming 'price' is the original column and 'log_price' needs to be created if not present
    # This part should ideally be handled during feature engineering if 'log_price' is a target.
    # For this subtask, if it's missing, let's create it for visualization purposes.
    if 'price' in housing.columns:
        housing['log_price'] = np.log1p(housing['price'])
    else:
        print("Error: 'price' or 'log_price' column not found in DataFrame. Cannot proceed with scatter plots against price.")

if 'log_price' in housing.columns:
    for feature in features_for_scatter_vs_price:
        if feature in housing.columns:
            p = (
                ggplot(housing, aes(x=feature, y='log_price'))
                + geom_point(alpha=0.3)
                + geom_smooth(method='lm', color='red', se=False) # Add a linear regression line
                + labs(title=f'Log Price vs. {feature}', x=feature, y='Log Price')
            )
            scatter_plots_vs_price.append(p)

    if len(scatter_plots_vs_price) > 0:
        print("\n--- Visualizing Feature Correlations with Log Price (Scatter Plots) ---")
        combined_scatter_plot_vs_price = gggrid(scatter_plots_vs_price, ncol=2) # 2 columns for scatter plots
        combined_scatter_plot_vs_price.show()
    else:
        print("No features found for scatter plotting against log_price.")
else:
    print("log_price not found in housing DataFrame for scatter plotting.")

--- Visualizing Feature Correlations with Log Price (Scatter Plots) ---

In [ ]:
important_features_for_pairwise = ['luxury_metric', 'sqft_living', 'lat', 'long', 'mean_price_zip']

# Filter for features actually present in the DataFrame
important_features_for_pairwise = [f for f in important_features_for_pairwise if f in housing.columns]

pairwise_plots = []
if len(important_features_for_pairwise) > 1: # Need at least two features for pairwise plots
    print("\n--- Exploring Pairwise Relationships Between Important Features ---")
    # Generate pairwise scatter plots
    for i in range(len(important_features_for_pairwise)):
        for j in range(i + 1, len(important_features_for_pairwise)):
            feature1 = important_features_for_pairwise[i]
            feature2 = important_features_for_pairwise[j]
            p = (
                ggplot(housing, aes(x=feature1, y=feature2))
                + geom_point(alpha=0.3)
                + geom_smooth(method='lm', color='blue', se=False) # Add a linear regression line
                + labs(title=f'{feature1} vs. {feature2}', x=feature1, y=feature2)
            )
            pairwise_plots.append(p)

    if len(pairwise_plots) > 0:
        combined_pairwise_plot = gggrid(pairwise_plots, ncol=2) # 2 columns for pairwise scatter plots
        combined_pairwise_plot.show()
    else:
        print("No pairs of important features found for pairwise plotting.")
else:
    print("Not enough important features found for pairwise plotting.")

--- Exploring Pairwise Relationships Between Important Features ---